config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :carts, except: [:index, :edit, :new, :create, :update, :destroy]
  resources :photos, except: [:edit, :new,:create, :update, :destroy]
  resources :users, except: [:index, :new, :create, :destroy]
  resources :orders, only: [:show]
  root 'photos#index'
  post 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
  post 'delete_photo', to: 'photos#delete_photo', as: 'delete_photo'


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create 
    
    @user = current_user
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      line_items: [{
        price_data: {
          currency: 'eur',
          product_data: {
            name: 'Mon Panier',
          },
          unit_amount: (@total*100).to_i,
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @user = current_user
    @cart = Cart.find_by(user_id: @user.id)
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    @order = Order.create!(user_id: @user.id)
    @order.fill_order(@cart)
    
    @cart.selections.destroy_all
    #il faut finir de compléter le Order et vider le panier
  end

  def cancel
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> <h1>Echec</h1> <p>Le paiement n'a pas abouti.</p> </div> 

app/views/checkout/success.html.erb
<div class="container text-center my-5"> 
<h1>Succès</h1> 
<p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p> 
<p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> 
<%= link_to "Voir ma commande", order_path(@order.id) %>
</div> 