config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :carts, except: [:index, :edit, :new, :create, :update, :destroy]
  resources :photos, except: [:edit, :new,:create, :update, :destroy]
  resources :users, except: [:index, :new, :create, :destroy]
  resources :orders, only: [:show]
  root 'photos#index'
  post 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
  post 'delete_photo', to: 'photos#delete_photo', as: 'delete_photo'


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders

  after_create :create_cart, :welcome_send
  

  def create_cart
    Cart.create!(
      user_id: self.id
    )
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy owner? ]
  before_action :owner?, only: [:destroy, :edit, :update]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(id: params[:id])
      unless @user
        flash[:alert] = "User not found."
        redirect_to root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:encrypted_password, :email, :first_name, :last_name, :cart_id)
    end

    def owner?
      
      unless (current_user == @user) && current_user
        flash[:danger] = "Impossible vous n'êtes pas le propriétaire du compte !"
        redirect_to "/"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="card mx-auto mt-5" style="max-width: 500px;">

 <div class="card-header">

 <h3 class="card-title text-center">Editing user</h3>
    
</div>


  <div class="card-body">
    <%= form_with(model: user, class: "form") do |form| %>
      <% if user.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control" %>
      </div>




      <div class="form-group text-center">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>
</div>
  

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Encrypted password:</strong>
    <%= user.encrypted_password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= user.cart.id %>
  </p>



</div>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", user_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h1> Mes commandes </h1>
<div class="container w-75 d-flex flex-column justify-content-start align-items-center">
  <ul class="list-group list-group-flush m-4">
    <%= render partial: "orders/order_summary", collection: @user.orders, as: :order %>
  </ul>
</div>