config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :carts, except: [:index, :edit, :new, :create, :update, :destroy]
  resources :photos, except: [:edit, :new,:create, :update, :destroy]
  resources :users, except: [:index, :new, :create, :destroy]
  resources :orders, only: [:show]
  root 'photos#index'
  post 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
  post 'delete_photo', to: 'photos#delete_photo', as: 'delete_photo'


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :selections, dependent: :destroy
  has_many :photos, through: :selections


  def add_photo_to_cart(photo)
    self.photos << photo
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy add_to_cart]
  before_action :owner?, only: [:show, :destroy, :edit, :update]
  before_action :total_of_cart, only: [:show]
  

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end


  def add_to_cart
    @photo = Photo.find(params[:id])

    if user_signed_in?
      @cart = Cart.find_by(user_id: current_user.id)
      @cart.add_photo_to_cart(@photo)
      redirect_to photos_path, notice: "Photo ajoutée au panier"
    else

      session[:photo] = @photo
      redirect_to new_user_session_path
    end
  end

  def total_of_cart
    
      @cart = Cart.find_or_create_by(user_id: current_user.id)
      @total_price_cart = 0
      @cart.photos.each do |photo|
        @total_price_cart += photo.price
      end
      return @total_price_cart
    
  end

  # GET /carts/1 or /carts/1.json
  def show
    @cart = Cart.find_by(user_id: current_user.id)
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.create(user_id: current_user.id)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), flash: { success: "Votre panier a été mis à jour." } }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, flash: { success: "La photo a été supprimée de votre panier." } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart     
      @cart = Cart.find_by(user_id: current_user.id) if current_user 
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def owner?
      @cart = set_cart
      unless @cart && current_user && current_user.id == @cart.user_id  
        flash[:danger] = "Impossible vous n'êtes pas le propriétaire de ce panier !"
        redirect_to "/"
      end
    end

  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<ul class="list-group list-group-flush m-4">
  <%= render partial: "photos/photo_row", collection: @cart.photos, as: :photo %>
  <li class="list-group-item d-flex gap-5 py-3 justify-content-end">
    <p class="mb-0">Total de la commande :</p>
    <strong class="text-nowrap"><%= number_to_currency(@total_price_cart, unit: "€", separator: ",", delimiter: "", format: "%n %u") %></strong>
    <%= button_to checkout_create_path(total: @total_price_cart), class: "btn btn-sm btn-outline-primary", remote: true , data: { turbo: "false" } do %>
      <%= render "/shared/buttons/confirm_order" %>
    <% end %>
  </li>
</ul>

app/views/carts/_empty_cart.html.erb
<p class="py-5 h4">Votre panier est vide.</p>
<img class="w-25" src="https://www.womansworld.com/wp-content/uploads/2018/05/sad-cat-luhu.jpg?resize=715,536">

<%= link_to root_path, class: "btn btn-sm btn-primary mt-4" do %>
  <%= render "/shared/buttons/view_photos" %>
<% end %>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div class="container d-flex flex-column justify-content-start align-items-center">
  <% if @cart.photos.any? %>
    <%= render @cart %>
  <% else %>
    <%= render "empty_cart" %>
  <% end %>
</div>