config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :carts, except: [:index, :edit, :new, :create, :update, :destroy]
  resources :photos, except: [:edit, :new,:create, :update, :destroy]
  resources :users, except: [:index, :new, :create, :destroy]
  resources :orders, only: [:show]
  root 'photos#index'
  post 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
  post 'delete_photo', to: 'photos#delete_photo', as: 'delete_photo'


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :selections, dependent: :destroy
  has_many :carts, through: :selections
  validates :title, presence: true

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  def delete_photo
    @cart = Cart.find_or_create_by(user_id: current_user.id)
    @photo = Photo.find(params[:id])
    @cart.selections.where(photo_id: params[:id]).first.delete
    redirect_to cart_path(current_user.cart), notice: "Votre photo #{@photo.title} est supprimé de votre panier."
  end

  # GET /photos/1 or /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:price, :title, :description, :url)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<h1 class="h2 mt-5"><%= photo.title %></h1>
<img src="<%= photo.image_url %>" alt="<%= photo.title %>" class="rounded img-fluid w-50 my-5">
<p><%= photo.description %></p>
<strong class="text-secondary"><%= photo.price %>&nbsp;€</strong>

app/views/photos/_photo_card.html.erb
<div id="photos" class="col">
  <div id="<%= dom_id photo %>" class="card">
    <img src="<%= photo.image_url %>" alt="<%= photo.title %>" class="card-img-top">
    <div class="position-absolute top-0 start-0 w-100">
      <%= link_to photo_path(photo), class: "btn btn-sm btn-primary m-3 position-absolute start-0" do %>
        <%= render "/shared/buttons/view" %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= photo.title %></h5>
      <p class="card-text"><%= photo.description %></p>
      <p class="card-text"></p>
      <div class="d-flex justify-content-between align-items-center">
        <strong class="text-secondary"><%= photo.price %>&nbsp;€</strong>
        <%= button_to add_to_cart_path(id: photo.id), class: "btn btn-sm btn-outline-primary" do %>
          <%= render "/shared/buttons/add_to_cart" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/_photo_row.html.erb
<li class="list-group-item list-group-item-action d-flex gap-3 py-3">
  <img src="<%= photo.image_url %>" alt="<%= photo.title %>" class="rounded w-25 img-fluid">
  <div class="d-flex gap-3 w-100 justify-content-around">
    <div class="d-flex justify-content-between flex-column">
      <div class="text-start">
        <h6 class="mb-0"><%= photo.title %></h6>
        <p class="mb-0 opacity-75"><%= photo.description %></p>
      </div>
    </div>
    <small class="opacity-50 text-nowrap"><%= number_to_currency(photo.price, unit: "€", separator: ",", delimiter: " ", format: "%n %u") %></small>
    <%= link_to photo_path(id: photo.id), class: "btn btn-sm btn-outline-primary align-self-start" do %>
      <%= render "/shared/buttons/view" %>
    <% end %>
    <%= button_to delete_photo_path(id: photo.id), data: {turbo_method: :delete}, class: "btn btn-sm btn-outline-primary" do %>
      <%= render "/shared/buttons/delete" %>
    <% end %>
  </div>
</li>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @photos.each do |photo| %>
        <%= render partial: "photo_card", locals: {photo: photo}%>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<div class="container d-flex flex-column justify-content-start align-items-center">
  <%= render @photo %>
  <%= button_to add_to_cart_path(id: @photo.id), class: "btn btn-sm btn-primary my-3" do %>
    <%= render "/shared/buttons/add_to_cart" %>
  <% end %>
</div>